### PR TITLE
Fix up og url with race id

### PR DESCRIPTION
**Pull request by johnwheffner**

### CODE REVIEW

**Comment by jyundt** [comment]
@johnwheffner 
Hey I think there is still a typo in this:
```
<meta property="og:url"           content="{{url_for('race.index', id=race.id)}}" />
```
should be:
```
<meta property="og:url"           content="{{url_for('race.details', id=race.id)}}" />
```

**Comment by johnwheffner** [comment]
Gr, you're right, want to fix it?  The problem with code that can't be tested.

**Comment by jyundt** [comment]
Yeah I'll fix it and try to test it with a fake FB account.

**Comment by jyundt** [comment]
Checkout #73 

I tested it with a fake FB account and I think it works fine.

-Jacob

**Pull request merged**
