### PR TITLE
Revamp standings page

### PR DESCRIPTION
**Pull request by johnwheffner**
- Show individual, team, mar all in the same view.
- Use links at the top rather than form to select view.

The rows at the top for selecting year and cat are ugly.  Ideas on making those prettier?

### CODE REVIEW

**Comment by johnwheffner** [comment]
I also improved the efficiency quite a bit, doing everything now from just a couple database queries rather than one per row.

**Comment by jyundt** [comment]
This looks pretty good. 

Do you care if I change some of the styling to use dropdowns + jQuery to change the table views? (rather than the pipe delimited list at the top of the page?)

**Comment by johnwheffner** [comment]
I'm not a big fan of the dropdowns (why hide something you can reasonably
show) but open to being convinced.  What I've got here is definitely a bit
fugly.

**Comment by jyundt** [comment]
Lemme ask @emilywools for some styling guidance.

**Comment by johnwheffner** [comment]
Previous years I could see using a dropdown.  Other categories is something
people will want a lot -- I was envisioning a tab-like interface.

**Comment by emilywools** [comment]
I am not sure what it looks like, but generally if you have fewer than 10 options, use radio buttons instead of a drop down, for the reason John said: don't hide content from the user.

Here's an article for reference: http://baymard.com/blog/drop-down-usability

**Comment by jyundt** [comment]
@emilywools 

Screencap:

image

**Comment by emilywools** [comment]
Yeah, this looks like it could be tabs/subtabs very easily.

**Comment by johnwheffner** [comment]
Pushed some changes using bootstrap elements.  I think this looks a fair bit better, though the right alignment looks weird with the "Season" drop-down for some reason.

**Comment by jyundt** [comment]
This looks way better, but I see what you mean about the alignment:

image

And right alignment:

image

The answer is probably: "add more div tags".

What about using pills for years and tabs for categories?

**Comment by johnwheffner** [comment]
I think pills are too bold for years.  We should have 15 years in here eventually.

Actually, the problem was one too many divs.

**Comment by jyundt** [comment]
@johnwheffner 

Changes pushed to server with v1.1.3.

**Pull request merged**
