### PR TITLE
Add new Results view similar to Standings

### PR DESCRIPTION
**Pull request by johnwheffner**

### CODE REVIEW

**Comment by jyundt** [comment]
This looks good, but a few comments:
- Based on one of the earlier slack conversations, can you delete the top level "Categories" (race_class) from the nav now that we are adding Results? (Or maybe the "Categories" cleanup should be a separate PR?)
- The "winner's" team as a clickable link, but the link points to the racer page, not the team. (I think you need something like this `<a href="{{url_for('team.details', id=result['winner'][2])}}">`
- There is an extra space between WINNER NAME , TEAM NAME
  - Maybe something like WINNER NAME [TEAM NAME]
- Is it worth displaying something that differentiates points races vs. non points races?

image

**Comment by jyundt** [comment]
Two other quick things:
- Maybe format the date to be consistent with the other date formats?  Something like MM/DD: `{{result['date'].strftime('%m/%d')}}`
  - Or MM/DD/YY  or DoW MM/DD ?
- Thoughts on sorting race results in reverse chronological order? E.g. most recent races first?

**Comment by johnwheffner** [comment]
Made some of those changes.  Didn't yet add a point-race annotation.  Let me know if you've got ideas on how to do that.

**Comment by johnwheffner** [comment]
One of my email responses didn't get through.

> Based on one of the earlier slack conversations, can you delete the top level "Categories" (race_class) from the nav now that we are adding Results? (Or maybe the "Categories" cleanup should be a separate PR?)

Will do in a later change.

> The "winner's" team as a clickable link, but the link points to the racer page, not the team. (I think you need something like this `<a href="{{url_for('team.details', id=result['winner'][2])}}">`

Good catch.

> There is an extra space between WINNER NAME , TEAM NAME
> Maybe something like WINNER NAME [TEAM NAME]

Done (with parens).

> Is it worth displaying something that differentiates points races vs. non points races?

Good idea.  How best to annotate that?

**Comment by jyundt** [comment]
> > Is it worth displaying something that differentiates points races vs. non points races?
> 
> Good idea. How best to annotate that?

I'll ask @emilywools, I'm guessing the "correct" answer is to have some type of iconography in the row to indicate points. In either case, we can add that later.

**edit**
Forgot to say that I checked out your fixup, lgtm.

I'll push to PRD shortly.

**Pull request merged**
