### PR TITLE
Proposal/request for comments: Add notes on release branching to the README

### PR DESCRIPTION
**Pull request by johnwheffner**
Implied here is that to release, you'd need to (currently) specify the release number or branch name on the ansible command line, or write a script to by default pull the latest.

### CODE REVIEW

**Comment by jyundt** [comment]
What is the benefit of creating release tag _and_ creating `releases` + `released` branches? Is that to keep track of what is "current" ?

**Comment by johnwheffner** [comment]
The idea is to keep the current released branch active for bugfixes.  When it's retired, tag it to freeze and save it.

**Comment by jyundt** [comment]
> The idea is to keep the current released branch active for bugfixes. When it's retired, tag it to freeze and save it.

This could be my github inexperience showing, but wouldn't you want to create the hotfix based off of the tagged release commit?  Or isn't that a thing with github pull requests?

**Comment by johnwheffner** [comment]
If you create a hotfix branch off a tag, where do you merge that branch?  (What does the pull request diff against and where does it land when you press the big green merge button?)

**Comment by johnwheffner** [comment]
(Excuse ugly ascii art)
```
Branch heads/tags denoted by *m, *r1, etc.

Do stuff on master
o -> o*m

Release r1
o -> o*m
      *r1

Do more stuff on master
o -> o -> o -> o*m
      *r1

Branch to fix a bug in release
o -> o -> o -> o*m
     |*r1
     v
     o*bf

Create pull request, merge bugfix to release branch
o -> o -> o -> o*m
     | \
     v  \
     o -> o*r1

Merge fixed release branch back into master
o -> o -> o -> o -> o*m
     | \          /
     v  \   /---/
     o -> o*r1

Do more stuff on matser
o -> o -> o -> o -> o -> o -> o*m
     | \          /
     v  \   /---/
     o -> o*r1

Release r2, tag/freeze r1
o -> o -> o -> o -> o -> o -> o*m
     | \          /            *r2
     v  \   /---/
     o -> o*tr1
```

**Comment by jyundt** [comment]
I'm seriously impressed by your ASCII art.

I see what you mean with having a separate branch for the hot fixes, that works for me.

Regarding the `releases` vs `released` branches, couldn't you accomplish the same thing with only one `release` branch + a tag (because we wouldn't ever have more than one release at a time)?  E.g. instead of creating a new "release branch" each time, we would merge `release` from `master`.

**Comment by johnwheffner** [comment]
Part of the idea with the individual release branches is to get the version in the ref name, so on release it can stamped somewhere that can be queried when running.

So yes, rather than use a different release name for each release branch, we could keep one release branch and tag each release point, and use that tag for deployment.  Each time cutting a release you'd probably want to make sure it's a "fast-forward" merge doing the merge from master -> release.  But that should naturally be the case if you've been diligent about merging release -> master.

**Pull request closed without merging**
