### PR TITLE
New logo on the front page

### PR DESCRIPTION
**Pull request by johnwheffner**

### CODE REVIEW

**Comment by johnwheffner** [comment]
image

**Comment by jyundt** [comment]
I'm cool with this but might want an approval from @emilywools

New landing page:

image


existing landing page:

image

**Comment by emilywools** [comment]
i think that's good but you should make the upper left the logo.. or
perhaps just the o like in slack?

**Comment by jyundt** [comment]
> i think that's good but you should make the upper left the logo.. or
perhaps just the o like in slack?

By "upper left" do you mean the navbar text currently labeled "The Oval"?  Replace "The Oval" with the stylized "O"?

**Comment by emilywools** [comment]
yes

**Comment by johnwheffner** [comment]
I thought the same.  Do you have the O?  I didn't find it anywhere.

**Comment by jyundt** [comment]
> I thought the same.  Do you have the O?  I didn't find it anywhere.

Yeah, I've got the "O", lemme find it and add it real fast.

**Comment by jyundt** [comment]
@emilywools 
Can you update the logo to have a transparent background?  I think it has a white background currently.

It's in The Oval gdrive folder: https://drive.google.com/drive/u/0/folders/0B6BDzbWjFxaVQkhsQnVhNW1lY0k

**Comment by emilywools** [comment]
you probably want it as a .png so its transparent...

**Comment by jyundt** [comment]
> you probably want it as a .png so its transparent...

It is a .png file.

**Comment by emilywools** [comment]
transparent .png attached.

**Comment by jyundt** [comment]
> transparent .png attached.

I'm sorry to be a pain, but I think the github mail processor stripped your attachment.

Can you email it to me directly or add it to the gdrive folder: https://drive.google.com/drive/u/0/folders/0B6BDzbWjFxaVQkhsQnVhNW1lY0k

**Comment by emilywools** [comment]
uploaded

**Comment by jyundt** [comment]
Thoughts on this?

image
image

**Comment by johnwheffner** [comment]
Looks good

**Pull request merged**
