### PR TITLE
Default course

### PR DESCRIPTION
**Pull request by johnwheffner**
Bring default course into the data model, removing hard-coding.

### CODE REVIEW

**Comment by jyundt** [comment]
@johnwheffner 
This looks good, but one minor style suggestion/comment for https://github.com/jyundt/oval/pull/41/commits/ce3f74dfff77c36ef3e4d4243d7915096a701e55#diff-e123d51ada385619dacf916aba8a172fR195

It might be easier to do something like 

```
Course.query.filter(Course.is_default==True).first().id
```

to get the ID of the default course. Thoughts?  

(I don't really feel strongly about it, but in terms of convention, I had been using .first() for similar situations.)

**Comment by johnwheffner** [comment]
Defensive programming.  There may not be any default course.

**Comment by jyundt** [comment]
Sorry, that's what I meant, something like:

```
default_course = Course.query.filter(Course.is_default==True).first()
if default_course:
    form.course_id.data = default_course.id
```

It's totally a minor stylistic thing and I really don't feel too strongly about it if you don't care.

**Comment by johnwheffner** [comment]
Ah, my assumption was that first() raised an exception if there weren't any.  (That's what other similar things usually do.)  I checked the doc and looks like it returns None if the result set is empty.

**Pull request merged**
