### PR TITLE
Racer filters

### PR DESCRIPTION
**Pull request by johnwheffner**
Add a couple filters to make the racer list a more manageable size.
Defaults to show only those active in the past year.

### CODE REVIEW

**Comment by jyundt** [comment]
This is a minor nitpick-y design thing, but is it possible to display the selected filters?  E.g. if I select "2015, Class B", can you display that (in addition to highlighting the selection on the button)?

Maybe change the H1 tag to something like "Racers - 2015 B" if selectors are present?

I'm open to any suggestions.

@emilywools thoughts?

image

**Comment by emilywools** [comment]
I really like how nordstrom does filters.
http://shop.nordstrom.com/c/handbag-accessories?origin=leftnav&top=66&flexi=8000786_60191574

After you select it, it appears (perhaps ours could be a little pill like
this) and has an x to remove it if you want to:

[image: Inline image 1]

**Comment by jyundt** [comment]
Ooo...I hadn't thought about pills.

**Comment by johnwheffner** [comment]
Not _super_ happy with this but I'm a bit happier with it from a ux perspective.  The jinja2 code could be better I think...

image

**Comment by emilywools** [comment]
i think if you move the x over to the right it will look better. are you
using an x icon or the letter x? it could be a little bigger or bolder i
think. font awesome is a good resource if you haven't checked it out
already.

good job guys!!

**Comment by johnwheffner** [comment]
BTW, the filtering logic is similar to Nordstrom's where filters in each group of filter (season, class) are ORed and each group is ANDed.

**Comment by johnwheffner** [comment]
I spent like two minutes looking for a good x.  Currently I'm using the "times" (&times;) symbol.  Suggestions?

**Comment by johnwheffner** [comment]
Here's the "remove" glyph from the bootstrap tookit: probably the right thing to use.
image

**Comment by emilywools** [comment]
yes that is probably better. it looks very bold though... i think it could
be smaller and bumped over to the right more? or perhaps the filtered item
can be bold (vs regular).

**Comment by johnwheffner** [comment]
Not sure the right way to bump to the right other than inserting a non-breaking space, which increases the horizontal space between label and X, but doesn't put the X far right.

**Comment by johnwheffner** [comment]
Compare with above:
image

**Comment by johnwheffner** [comment]
... and with bold
image

**Comment by johnwheffner** [comment]
I think I like the last one best.  I'll go with that unless anyone disagrees.  Thanks @emilywools!

**Comment by emilywools** [comment]
yep agree. looks good!!

**Comment by jyundt** [comment]
This looks good, but I think the filter logic _might_ be a bit confusing.  (Or I could be overthinking it.)

As an example, I would think that using this filter critera: "2012, 2013, 2014, 2015, 2016, A" would show me _onl_y A racers that have participated in all of those seasons (2012-2016).

But, if I understand it correctly it is showing all 2012 A racers + 2013 A racers + 2014 A racers...etc, right?

image

**Comment by johnwheffner** [comment]
Bugs me some too but the logic is the only choice that makes sense.  Options are get rid of the pills or distinguish visually by group.  This style is good enough for Nordstrom and others I've seen, probably we're over thinking it.

**Comment by jyundt** [comment]
Alright, LGTM.

**Review by jyundt — APPROVED** [review]

**Pull request merged**
