### PR TITLE
Competition ranking for standings

### PR DESCRIPTION
**Pull request by johnwheffner**
Fixes issue #72

### CODE REVIEW

**Comment by jyundt** [comment]
There are a lot less underscores, I like that.

Do you want to wait for an official ACA ruling on "standings logic" before merging this?  Just in case we made some incorrect assumptions?

Other than possibly waiting for an official ruling: LGTM

**Comment by johnwheffner** [comment]
No need to wait on a ruling.  Aside from the little change I slipped in there capping tiebreaks at 8th place, which matches what Jack's been doing, the bulk of this change is just to handle the case when we don't have a tiebreak in place.  I would like to get an answer on MAR standings.  Based on what I see Jack put up, he's using individual standings as the tiebreak, but I'd like to double check that before implementing.

One thing that occurred to me is that we may ultimately want, like for points, to allow an override for season standings, in case we don't correctly capture all the rules, which may in fact change over time.

**Comment by jyundt** [comment]
> One thing that occurred to me is that we may ultimately want, like for points, to allow an override for season standings, in case we don't correctly capture all the rules, which may in fact change over time.

Would you want to store these standings in the DB instead of programmaticly generating them each time?

If so, that might make "the trophy case" view a bit easier.

**Comment by johnwheffner** [comment]
> Would you want to store these standings in the DB instead of programmaticly generating them each time?

No, I don't think so.  I think I'm talking about one-off fixups that apply to a specific date.  Basically for making the final standings work correctly for past seasons in case something's off with the encoded rules.  This'll be a bit of a pain, so it's not at the top of my to-do list.

**Pull request merged**
