### PR TITLE
Races cleanup

### PR DESCRIPTION
**Pull request by johnwheffner**
A batch of changes to clean up the list views of races a bit, especially for non-admin users.

### CODE REVIEW

**Comment by jyundt** [comment]
For the recently changed Categories and Course types, existing data is not displayed. Is this intentional?

image

image

Also @emilywools saw the "+" glyphicon for the Points columns and had a few suggestions. Adding her to the PR.

**Comment by johnwheffner** [comment]
Yea, intentional.  The idea is these pages are for admin of those things not viewing races.

**Comment by johnwheffner** [comment]
Though I didn't think there would still be headings.. That doesn't look right.

**Comment by johnwheffner** [comment]
Right.. that's a bug.

**Comment by johnwheffner** [comment]
Should be fixed.

**Comment by jyundt** [comment]
Cool, much better. lgtm.

**Comment by jyundt** [comment]
@johnwheffner pushed to server with v1.1.4

**Pull request merged**
