### PR TITLE
We don't know season pass class; convert to boolean

### PR DESCRIPTION
**Pull request by johnwheffner**

### CODE REVIEW

**Comment by jyundt** [comment]
Thanks for fixing this, I misunderstood the Season Pass thing.

I thought a [Season Pass](http://acaracing.com/pass17.html) was purchased "per category" but it looks like it can be used "once per week" regardless of category.

```
2017 ACA Season Pass
The 2017 ACA Season Pass is good at all 2017 Tuesday or Wednesday evening ACA criteriums at the
Bud Harris Cycling Park on Washington Blvd. This includes 20 Tuesday (April 11-August 22, 2017)
races or 20 Wednesday races (April 12-August 23, 2017) for only $210. Juniors (U18) are 
discounted to $125. This cost includes a $30 ACA Membership for 2017. That's 20 races
for the net cost of $9.00 per race for the adult pass.
The pass is interchangeable between nights, but you can use it for only one race per week.
```

**Review by jyundt — APPROVED** [review]
LGTM

**Comment by johnwheffner** [comment]
Would you mind letting me merge pull requests by default?  I often (as in
this case) like to fix them up post review.

**Comment by jyundt** [comment]
Oh yikes, sorry about that. Do you want me to re-open this?

**Comment by johnwheffner** [comment]
No big deal, I'm just picky about how final commits are arranged; I usually
do an interactive rebase to get a clean history without a squash.

**Pull request merged**
